baseURL = 'https://beanbytes.fr'
languageCode = 'fr'
title = 'BeanBytes'
description = 'description' 
theme = 'mytheme'

  [params]
    author = "Maxime Herbaut"
  
  [frontmatter]
    date = ["date", "publishDate", "lastmod"]
    lastmod = ["lastmod", ":fileModTime", ":default"]
