baseURL = 'https://maximeherbaut.com'
languageCode = 'fr' 
title = 'Maxime Herbaut'
theme = 'mytheme'
disableKinds = ["taxonomy", "taxonomyTerm"]

  [params]
    description = "Site professionnel de Maxime Herbaut, product manager / CPO freelance, basé à Lille."
    author = "Maxime Herbaut"
    email = "maxime@herbaut.me"
    github = "https://github.com/herbautmax"
    linkedin = "https://www.linkedin.com/in/maximeherbaut/"
    calendly = "https://calendly.com/maximeherbaut/30min"
  
  [frontmatter]
    date = ["date", "publishDate", "lastmod"]
    lastmod = ["lastmod", ":fileModTime", ":default"]